# Generated by Django 5.2.8 on 2026-03-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='return_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
