# Generated by Django 5.2.8 on 2026-03-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_participant_return_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='steem_dollars',
            new_name='steem',
        ),
    ]
