# Generated by Django 5.2.8 on 2026-03-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_rename_steem_dollars_participant_steem'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='comment_count_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='post_count_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='steem_total_final',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='vote_count_final',
            field=models.IntegerField(default=0),
        ),
    ]
