# Generated by Django 5.2.8 on 2026-04-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_participant_comment_count_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user_vested_level',
            field=models.IntegerField(default=1),
        ),
    ]
